services:
  warpnet1:
    container_name: warpnet-mainnet-1
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4001
      - NODE_HOST_V4=207.154.221.44
      - NODE_SEED=warpnet1
      - NODE_NETWORK=warpnet
      - LOGGING_LEVEL=info

  warpnet2:
    container_name: warpnet-mainnet-2
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4002
      - NODE_HOST_V4=207.154.221.44
      - NODE_SEED=warpnet2
      - NODE_NETWORK=warpnet
      - LOGGING_LEVEL=info

  warpnet3:
    container_name: warpnet-mainnet-3
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4003
      - NODE_SEED=warpnet3
      - NODE_HOST_V4=207.154.221.44
      - NODE_NETWORK=warpnet
      - LOGGING_LEVEL=info


# TODO: I NEED AN EXPENSIVE AND POWERFUL MACHINE FOR THAT!
#  warpnet-moderator:
#    container_name: moderator1
#    image: ghcr.io/warp-net/warpnet-moderator:latest
#    network_mode: host
#    restart: always
#    environment:
#      - NODE_PORT=4004
#      - NODE_HOST_V4=207.154.221.44
#      - NODE_NETWORK=warpnet
#      - LOGGING_LEVEL=info
#      - NODE_SEED=warpnet-moderator1

