services:
  warpnet11:
    container_name: warpnet-testnet-1
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4011
      - NODE_HOST_V4=207.154.221.44
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet1

  warpnet22:
    container_name: warpnet-testnet-2
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4022
      - NODE_HOST_V4=207.154.221.44
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet2

  warpnet33:
    container_name: warpnet-testnet-3
    image: ghcr.io/warp-net/warpnet-bootstrap:latest
    network_mode: host
    restart: always
    environment:
      - NODE_PORT=4033
      - NODE_HOST_V4=207.154.221.44
      - NODE_NETWORK=testnet
      - LOGGING_LEVEL=info
      - NODE_SEED=warpnet3

#  warpnet-moderator-test:
#    container_name: moderator-testnet
#    image: ghcr.io/warp-net/warpnet-moderator:latest
#    network_mode: host
#    restart: always
#    environment:
#      - NODE_PORT=4044
#      - NODE_HOST_V4=207.154.221.44
#      - NODE_NETWORK=testnet
#      - LOGGING_LEVEL=info
#      - NODE_SEED=warpnet-moderator1
#    volumes:
#      - /root/.warpdata2:/root/.warpdata2:rw


